version: "3.5"

services:
  tester:
    container_name: tester
    image: golang:1.14
    working_dir: /tmp/goshimmer/tools/integration-tests/tester
    entrypoint: go test ./tests -v -mod=readonly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../..:/tmp/goshimmer:ro
      - ../logs:/tmp/logs
      - goshimmer-testing-cache:/go

volumes:
  goshimmer-testing-cache:
    name: goshimmer-testing-cache